name: template
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Justera beroende på vilken SDK-version du använder (detta funkar för Flutter 3.x)

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # HTTP-anrop för API
  cupertino_icons: ^1.0.8  # Cupertino-ikoner för iOS-stil

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Rekommenderade lints för bra kodstandard

flutter:
  uses-material-design: true  # Inkluderar Material Icons för ikoner i appen


